### ISSUE TITLE
The project is no longer working with the recent `awesome_panel_extensions`

### ISSUE THREAD

**Issue by cloud-rocket** [MarcSkovMadsen/awesome-analytics-apps-template#6]
Any ideas?

Thanks

Running with `invoke site.serve` triggers the following exception

```
ERROR:bokeh.application.application:Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x7f4419cc9430>: 'TemplateConfig' object has no attribute 'js_files'
File "base.py", line 512, in _template_resources:
for name, js in self.config.js_files.items(): Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bokeh/application/handlers/code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "/home/meir/web-dashboard/awesome-analytics-apps-template/src/apps/home/app.py", line 31, in <module>
    view().servable()
  File "/usr/local/lib/python3.8/dist-packages/panel/viewable.py", line 315, in servable
    self.server_doc(title=title, location=True)
  File "/usr/local/lib/python3.8/dist-packages/panel/template/base.py", line 292, in server_doc
    return self._init_doc(doc, title=title, location=location)
  File "/usr/local/lib/python3.8/dist-packages/panel/template/base.py", line 464, in _init_doc
    self._update_vars()
  File "/usr/local/lib/python3.8/dist-packages/panel/template/base.py", line 613, in _update_vars
    self._render_variables['template_resources'] = self._template_resources()
  File "/usr/local/lib/python3.8/dist-packages/panel/template/base.py", line 512, in _template_resources
    for name, js in self.config.js_files.items():
AttributeError: 'TemplateConfig' object has no attribute 'js_files'
```

**Comment by Axeldnahcram** [comment]
@cloud-rocket I think the template used in the example is not correct. You should change the ListTemplate to GalleryTemplate
I have proposed a PR here. I would open a PR but I do not think I have the requested credentials.
